// Code generated by sqlc. DO NOT EDIT.
// source: refresh_tokens.sql

package models

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO artist_sync_refresh_tokens (user_name, expired_at, value)
VALUES ($1, $2, $3)
ON CONFLICT (user_name)
DO UPDATE SET value = $3, expired_at = $2
`

type CreateRefreshTokenParams struct {
	UserName  string    `json:"user_name"`
	ExpiredAt time.Time `json:"expired_at"`
	Value     string    `json:"value"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.UserName, arg.ExpiredAt, arg.Value)
	return err
}
