// Code generated by sqlc. DO NOT EDIT.
// source: subscriptions.sql

package models

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscriptions (user_name, artist_id)
SELECT $1, artist_id FROM spotify_artist_associations
WHERE store_name = $2 AND store_id = $3
ON CONFLICT DO NOTHING
`

type CreateSubscriptionParams struct {
	UserName  string `json:"user_name"`
	StoreName string `json:"store_name"`
	StoreID   string `json:"store_id"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createSubscription, arg.UserName, arg.StoreName, arg.StoreID)
	return err
}
