on:
  push:
    branches:
      - master
      - develop

name: Build and push latest image to github packages and docker hub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Install artisync binaries
        run: |
          go install -v ./cmd/artisync-api/...
          go install -v ./cmd/artisync-daily/...
          go install -v ./cmd/artisync-sync/...

      - name: Test whole code
        run: |
          make t

      - name: Install and run lints
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE v1.31.0

          $GITHUB_WORKSPACE/golangci-lint -v run

          go get -u github.com/mgechev/revive
          $(go env GOPATH)/bin/revive --config ./.revive.toml --formatter stylish ./cmd/...
          $(go env GOPATH)/bin/revive --config ./.revive.toml --formatter stylish ./internal/...
          $(go env GOPATH)/bin/revive --config ./.revive.toml --formatter stylish ./pkg/...

      - name: Build the Docker image
        run: |
          docker build \
            --file ./Dockerfile \
            --build-arg RELEASE=${GITHUB_REF##*/} \
            --build-arg COMMIT=${GITHUB_SHA} \
            --build-arg BUILD_TIME=$(date -u '+%Y-%m-%dT%H:%M:%S') \
            --tag musicmash/artisync-builder:latest \
            .
          docker build \
            --file ./build/api/Dockerfile \
            --tag ghcr.io/musicmash/artisync-api:latest \
            .
          docker build \
            --file ./build/daily/Dockerfile \
            --tag ghcr.io/musicmash/artisync-daily:latest \
            .
          docker build \
            --file ./build/sync/Dockerfile \
            --tag ghcr.io/musicmash/artisync-sync:latest \
            .

      - name: Login to github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN

      - name: Push image to github
        run: |
          docker push ghcr.io/musicmash/artisync-api:latest
          docker push ghcr.io/musicmash/artisync-daily:latest
          docker push ghcr.io/musicmash/artisync-sync:latest

      - name: Logout from github
        run: |
          docker logout docker.pkg.github.com
