on:
  push:
    branches:
      - master
      - develop

name: Build and push latest image to github packages and docker hub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install artisync binaries
        run: make install

      - name: Test whole code
        run: make test

      - name: Install and run lints
        run: make lint

      - name: Build artisync builder image
        run: |
          docker build \
            --file ./Dockerfile \
            --build-arg RELEASE=${GITHUB_REF##*/} \
            --build-arg COMMIT=${GITHUB_SHA} \
            --build-arg BUILD_TIME=$(date -u '+%Y-%m-%dT%H:%M:%S') \
            --tag musicmash/artisync-builder:latest \
            .
      - name: Build artisync images
          docker build --file ./build/api/Dockerfile   --tag ghcr.io/musicmash/artisync-api:latest .
          docker build --file ./build/daily/Dockerfile --tag ghcr.io/musicmash/artisync-daily:latest .
          docker build --file ./build/sync/Dockerfile  --tag ghcr.io/musicmash/artisync-sync:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image to GitHub Container Registry
        run: |
          docker push ghcr.io/musicmash/artisync-api:latest
          docker push ghcr.io/musicmash/artisync-daily:latest
          docker push ghcr.io/musicmash/artisync-sync:latest
