on:
  push:
    tags:
      - "v*"

name: Build and push release image to github packages and docker hub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install artisync binaries
        run: make install

      - name: Test whole code
        run: make test

      - name: Install and run lints
        run: make lint

      - name: Build the Docker image
        run: |
          docker build \
            --file ./Dockerfile \
            --build-arg RELEASE=${GITHUB_REF##*/} \
            --build-arg COMMIT=${GITHUB_SHA} \
            --build-arg BUILD_TIME=$(date -u '+%Y-%m-%dT%H:%M:%S') \
            --tag musicmash/artisync-builder:latest \
            .
          docker build \
            --file ./build/api/Dockerfile \
            --tag docker.pkg.github.com/${{ github.repository }}/artisync-api:${GITHUB_REF##*/} \
            .
          docker build \
            --file ./build/daily/Dockerfile \
            --tag docker.pkg.github.com/${{ github.repository }}/artisync-daily:${GITHUB_REF##*/} \
            .
          docker build \
            --file ./build/sync/Dockerfile \
            --tag docker.pkg.github.com/${{ github.repository }}/artisync-sync:${GITHUB_REF##*/} \
            .

      - name: Login to github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN

      - name: Push image to github
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}/artisync-api:${GITHUB_REF##*/}
          docker push docker.pkg.github.com/${{ github.repository }}/artisync-daily:${GITHUB_REF##*/}
          docker push docker.pkg.github.com/${{ github.repository }}/artisync-sync:${GITHUB_REF##*/}

      - name: Logout from github
        run: |
          docker logout docker.pkg.github.com
